/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodorderingsystemınterface;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author qwe
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTextFrame = new javax.swing.JTextField();
        userPasswordTextFrame = new javax.swing.JPasswordField();
        registerUserButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Food Ordering System");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        usernameTextFrame.setText("Username");
        usernameTextFrame.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTextFrameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFrameFocusLost(evt);
            }
        });
        usernameTextFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFrameActionPerformed(evt);
            }
        });

        userPasswordTextFrame.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userPasswordTextFrameFocusGained(evt);
            }
        });

        registerUserButton.setText("Register");
        registerUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(registerUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userPasswordTextFrame)
                                .addComponent(usernameTextFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTextFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userPasswordTextFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUserButton)
                    .addComponent(loginButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFrameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFrameActionPerformed

    private void registerUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserButtonActionPerformed
        RegisterFrame registerFrame = new RegisterFrame();
        registerFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerUserButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        String line = "";  
        String splitBy = ","; 
        ArrayList<User> userList = new ArrayList<User>();

        //file reading
        try   
        {  
        //parsing a CSV file into BufferedReader class constructor  
        BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\bulen\\Desktop\\FoodOrderingSystemInterface\\FoodOrderingSystemInterface\\src\\foodorderingsystemınterface\\users.txt"));

        while ((line = br.readLine()) != null)   //returns a Boolean value  
        {  
        String[] User = line.split(splitBy);		// use comma as separator 
        userList.add(new User(User[0], User[1], User[2], User[3], User[4], User[5]));

        }  
        }   
        catch (IOException e)   
        {  
        e.printStackTrace();  
        }  
        boolean loginCheck=false;
        for(int i =0;i<userList.size();i++){
            if(userList.get(i).getName().equals(usernameTextFrame.getText())&& userList.get(i).getPassword().equals(userPasswordTextFrame.getText())){
                loginCheck=true;
            }
        }
        if(loginCheck==true){
            RestaurantListFrame restaurantListFrame = new RestaurantListFrame();
            restaurantListFrame.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "Login Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameTextFrameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFrameFocusGained
        if(usernameTextFrame.getText().equals("Username")){
            usernameTextFrame.setText("");
        }
    }//GEN-LAST:event_usernameTextFrameFocusGained

    private void usernameTextFrameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFrameFocusLost
        if(usernameTextFrame.getText().equals("")){
            usernameTextFrame.setText("Username");
        }
    }//GEN-LAST:event_usernameTextFrameFocusLost

    private void userPasswordTextFrameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userPasswordTextFrameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordTextFrameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginFrame loginframe = new LoginFrame();
                loginframe.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton registerUserButton;
    private javax.swing.JPasswordField userPasswordTextFrame;
    private javax.swing.JTextField usernameTextFrame;
    // End of variables declaration//GEN-END:variables
}
